version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - app-network

  # rabbitmq:
  #   image: 'rabbitmq:management'
  #   env_file:
  #     - .env
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672'
  #   networks:
  #     - app-network

  chatapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules/
    command: yarn start:dev
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      # - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
